### ISSUE TITLE
should be using namespace::autoclean

### ISSUE THREAD

**Issue by karenetheridge** [karupanerura/Aniki#11]
namespace::sweep is now obsolete and namespace::autoclean handles more cases, more properly. Anything using Moose, Moo or Mouse should absolutely be using namespace::autoclean; for a few situations (e.g. exporter classes) namespace::clean might be preferable, but a ticket reporting the issue would still be very much welcomed.

(0.16 is the version that dropped the loading of Class::MOP to introspect Moo classes.)

**Comment by karupanerura** [comment]
Thank you for your notice. switched it after next version!
