### ISSUE TITLE
SQL error when calling update without data

### ISSUE THREAD

**Issue by GeJ** [karupanerura/Aniki#12]
I stumbled upon an issue today while working with Aniki. The root of the problem is this : 
When running the following code :
`$db->update($row, +{})`
Aniki create the following SQL request : 
`UPDATE my_table SET WHERE ...`
At least under SQLite, this borks loudly complaining that there's an error in the SQL before the WHERE (I had to use trace to see the SQL statement). Now, I think it would be nice to handle this kind of error, but I'm not sure why.
Should the method `croak`, or just `return undef`? And also, since we're at least attempting to make an update (even with no data) should Aniki activate the triggers or not?
I'm willing to work on a PR following your suggestions on the issue.

**Comment by karupanerura** [comment]
Thank you for your notice.
I'll fix it in near days.
