### ISSUE TITLE
updateの仕様について

### ISSUE THREAD

**Issue by mamimumemoomoo** [karupanerura/Aniki#14]
`update($row => +{ bar => 1 });`で更新した際に$rowオブジェクト自身が更新できればと思います。
insertでは`insert_and_fetch_row`や`insert_and_emulate_row`がありますが、updateではそれと似たように$rowオブジェクト自身を更新するような処理を今後実装する予定ありますでしょうか？
リレーションまわりで考慮が必要そうですが、技術的な観点で実装を断念している場合はその理由もご教授いただけると幸いです。

**Comment by karupanerura** [comment]
ドキュメントに明記していなかったことに今気づいたのですが、AnikiのポリシーとしてRow ObjectはImmutableであるべきだと考えています。
例に示して頂いたものでも、AutoCommit環境下ではupdateした値は実際にDBに入っている値と行にはいっている値は違う可能性があります。（updateしたタイミングでトランザクションがコミットされるため、並行する他のトランザクションにより即座に変更される可能性があるためです。トランザクション内でlocking readからupdateを行い一貫性を持って扱うケースでは問題がありません）
リレーションまわりに関しても、ご提示頂いたとおり、他のRow Objectからどのように関連づいているか等の考慮が必要になります。
Row ObjectがImmutableであればその点はシンプルになります。
ただ、 `insert_and_fetch_row` や `insert_and_emulate_row` のように新しいRow Objectを作るインターフェースもあって良いかもしれません。
もしそれであなたが抱える問題が解決するのであれば検討しますがいかがですか？

**Comment by mamimumemoomoo** [comment]
AutoCommitがOFFのトランザクションを明示的に貼った状況を想定しております。
リレーションについても新しいRow Objectから再度リレーションを張るコストを許容できるので、updateすると渡したものと同じimmutableな新しいRow Object作って返してくれるインターフェースがあればなと思います。
一先ず、こちらでP-Rを出そうと思っていますが大丈夫でしょうか？

**Comment by karupanerura** [comment]
歓迎します！

**Comment by karupanerura** [comment]
Created #15
